In [1]:
! pip install -r requirements.txt

Collecting altair==6.1.0 (from -r requirements.txt (line 1))
  Using cached altair-6.1.0-py3-none-any.whl.metadata (11 kB)
Collecting annotated-doc==0.0.4 (from -r requirements.txt (line 2))
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting anyio==4.13.0 (from -r requirements.txt (line 3))
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting argon2-cffi==25.1.0 (from -r requirements.txt (line 4))
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting argon2-cffi-bindings==25.1.0 (from -r requirements.txt (line 5))
  Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (7.4 kB)
Collecting arrow==1.4.0 (from -r requirements.txt (line 6))
  Using cached arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: asttokens==3.0.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (3.0.1)
Collecting async-lru==2.3.0 (from -r requirements.txt (line 8))
  Using cached async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting attrs==26.1.0 (from -r requirements.txt (line 9))
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting babel==2.18.0 (from -r requirements.txt (line 10))
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4==4.14.3 (from -r requirements.txt (line 11))
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach==6.3.0 (from -r requirements.txt (line 12))
  Using cached bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting blinker==1.9.0 (from -r requirements.txt (line 13))
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools==7.1.4 (from -r requirements.txt (line 14))
  Using cached cachetools-7.1.4-py3-none-any.whl.metadata (5.5 kB)
Collecting certifi==2026.5.20 (from -r requirements.txt (line 15))
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi==2.0.0 (from -r requirements.txt (line 16))
  Using cached cffi-2.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.6 kB)
Collecting charset-normalizer==3.4.7 (from -r requirements.txt (line 17))
  Using cached charset_normalizer-3.4.7-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting click==8.4.1 (from -r requirements.txt (line 18))
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: comm==0.2.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 19)) (0.2.3)
Collecting contourpy==1.3.3 (from -r requirements.txt (line 20))
  Using cached contourpy-1.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cuda-bindings==13.3.0 (from -r requirements.txt (line 21))
  Using cached cuda_bindings-13.3.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting cuda-pathfinder==1.5.5 (from -r requirements.txt (line 22))
  Using cached cuda_pathfinder-1.5.5-py3-none-any.whl.metadata (1.9 kB)
Collecting cuda-toolkit==13.0.2 (from -r requirements.txt (line 23))
  Using cached cuda_toolkit-13.0.2-py2.py3-none-any.whl.metadata (9.4 kB)
Collecting cycler==0.12.1 (from -r requirements.txt (line 24))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: debugpy==1.8.20 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 25)) (1.8.20)
Requirement already satisfied: decorator==5.3.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 26)) (5.3.1)
Collecting defusedxml==0.7.1 (from -r requirements.txt (line 27))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: executing==2.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (2.2.1)
Collecting fastjsonschema==2.21.2 (from -r requirements.txt (line 29))
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting filelock==3.29.0 (from -r requirements.txt (line 30))
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting fonttools==4.63.0 (from -r requirements.txt (line 31))
  Using cached fonttools-4.63.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (118 kB)
Collecting fqdn==1.5.1 (from -r requirements.txt (line 32))
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting fsspec==2026.4.0 (from -r requirements.txt (line 33))
  Using cached fsspec-2026.4.0-py3-none-any.whl.metadata (10 kB)
Collecting gitdb==4.0.12 (from -r requirements.txt (line 34))
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting GitPython==3.1.50 (from -r requirements.txt (line 35))
  Using cached gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Collecting h11==0.16.0 (from -r requirements.txt (line 36))
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet==1.5.0 (from -r requirements.txt (line 37))
  Using cached hf_xet-1.5.0-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpcore==1.0.9 (from -r requirements.txt (line 38))
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting httptools==0.8.0 (from -r requirements.txt (line 39))
  Using cached httptools-0.8.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (3.5 kB)
Collecting httpx==0.28.1 (from -r requirements.txt (line 40))
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting huggingface_hub==1.17.0 (from -r requirements.txt (line 41))
  Using cached huggingface_hub-1.17.0-py3-none-any.whl.metadata (14 kB)
Collecting idna==3.17 (from -r requirements.txt (line 42))
  Using cached idna-3.17-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: ipykernel==7.2.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 43)) (7.2.0)
Requirement already satisfied: ipython==9.14.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 44)) (9.14.0)
Requirement already satisfied: ipython_pygments_lexers==1.1.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 45)) (1.1.1)
Collecting isoduration==20.11.0 (from -r requirements.txt (line 46))
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting itsdangerous==2.2.0 (from -r requirements.txt (line 47))
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jedi==0.20.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 48)) (0.20.0)
Collecting Jinja2==3.1.6 (from -r requirements.txt (line 49))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting joblib==1.5.3 (from -r requirements.txt (line 50))
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting json5==0.14.0 (from -r requirements.txt (line 51))
  Using cached json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonpointer==3.1.1 (from -r requirements.txt (line 52))
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting jsonschema==4.26.0 (from -r requirements.txt (line 53))
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting jsonschema-specifications==2025.9.1 (from -r requirements.txt (line 54))
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-events==0.12.1 (from -r requirements.txt (line 55))
  Using cached jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-lsp==2.3.1 (from -r requirements.txt (line 56))
  Using cached jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: jupyter_client==8.8.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 57)) (8.8.0)
Requirement already satisfied: jupyter_core==5.9.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 58)) (5.9.1)
Collecting jupyter_server==2.19.0 (from -r requirements.txt (line 59))
  Using cached jupyter_server-2.19.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyter_server_terminals==0.5.4 (from -r requirements.txt (line 60))
  Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab==4.5.7 (from -r requirements.txt (line 61))
  Using cached jupyterlab-4.5.7-py3-none-any.whl.metadata (16 kB)
Collecting jupyterlab_pygments==0.3.0 (from -r requirements.txt (line 62))
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting jupyterlab_server==2.28.0 (from -r requirements.txt (line 63))
  Using cached jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting kiwisolver==1.5.0 (from -r requirements.txt (line 64))
  Using cached kiwisolver-1.5.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting lark==1.3.1 (from -r requirements.txt (line 65))
  Using cached lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting markdown-it-py==4.2.0 (from -r requirements.txt (line 66))
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting MarkupSafe==3.0.3 (from -r requirements.txt (line 67))
  Using cached markupsafe-3.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Collecting matplotlib==3.10.9 (from -r requirements.txt (line 68))
  Using cached matplotlib-3.10.9-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Requirement already satisfied: matplotlib-inline==0.2.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 69)) (0.2.2)
Collecting mdurl==0.1.2 (from -r requirements.txt (line 70))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting mistune==3.2.1 (from -r requirements.txt (line 71))
  Using cached mistune-3.2.1-py3-none-any.whl.metadata (1.9 kB)
Collecting mpmath==1.3.0 (from -r requirements.txt (line 72))
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting narwhals==2.21.2 (from -r requirements.txt (line 73))
  Using cached narwhals-2.21.2-py3-none-any.whl.metadata (16 kB)
Collecting nbclient==0.10.4 (from -r requirements.txt (line 74))
  Using cached nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting nbconvert==7.17.1 (from -r requirements.txt (line 75))
  Using cached nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Collecting nbformat==5.10.4 (from -r requirements.txt (line 76))
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: nest-asyncio==1.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 77)) (1.6.0)
Collecting networkx==3.6.1 (from -r requirements.txt (line 78))
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting notebook_shim==0.2.4 (from -r requirements.txt (line 79))
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting numpy==2.4.6 (from -r requirements.txt (line 80))
  Using cached numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting nvidia-cublas==13.1.1.3 (from -r requirements.txt (line 81))
  Using cached nvidia_cublas-13.1.1.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-cupti==13.0.85 (from -r requirements.txt (line 82))
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc==13.0.88 (from -r requirements.txt (line 83))
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime==13.0.96 (from -r requirements.txt (line 84))
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu13==9.20.0.48 (from -r requirements.txt (line 85))
  Using cached nvidia_cudnn_cu13-9.20.0.48-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
Collecting nvidia-cufft==12.0.0.61 (from -r requirements.txt (line 86))
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cufile==1.15.1.6 (from -r requirements.txt (line 87))
  Using cached nvidia_cufile-1.15.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand==10.4.0.35 (from -r requirements.txt (line 88))
  Using cached nvidia_curand-10.4.0.35-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver==12.0.4.66 (from -r requirements.txt (line 89))
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse==12.6.3.3 (from -r requirements.txt (line 90))
  Using cached nvidia_cusparse-12.6.3.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu13==0.8.1 (from -r requirements.txt (line 91))
  Using cached nvidia_cusparselt_cu13-0.8.1-py3-none-manylinux2014_x86_64.whl.metadata (12 kB)
Collecting nvidia-nccl-cu12==2.30.4 (from -r requirements.txt (line 92))
  Using cached nvidia_nccl_cu12-2.30.4-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nccl-cu13==2.29.7 (from -r requirements.txt (line 93))
  Using cached nvidia_nccl_cu13-2.29.7-py3-none-manylinux_2_18_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvjitlink==13.0.88 (from -r requirements.txt (line 94))
  Using cached nvidia_nvjitlink-13.0.88-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvshmem-cu13==3.4.5 (from -r requirements.txt (line 95))
  Using cached nvidia_nvshmem_cu13-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx==13.0.85 (from -r requirements.txt (line 96))
  Using cached nvidia_nvtx-13.0.85-py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: packaging==26.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 97)) (26.2)
Collecting pandas==3.0.3 (from -r requirements.txt (line 98))
  Using cached pandas-3.0.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pandocfilters==1.5.1 (from -r requirements.txt (line 99))
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: parso==0.8.7 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 100)) (0.8.7)
Requirement already satisfied: pexpect==4.9.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 101)) (4.9.0)
Collecting pillow==12.2.0 (from -r requirements.txt (line 102))
  Using cached pillow-12.2.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Requirement already satisfied: platformdirs==4.10.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 103)) (4.10.0)
Collecting plotly==6.7.0 (from -r requirements.txt (line 104))
  Using cached plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting prometheus_client==0.25.0 (from -r requirements.txt (line 105))
  Using cached prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: prompt_toolkit==3.0.52 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 106)) (3.0.52)
Collecting protobuf==7.35.0 (from -r requirements.txt (line 107))
  Using cached protobuf-7.35.0-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: psutil==7.2.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 108)) (7.2.2)
Requirement already satisfied: ptyprocess==0.7.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 109)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 110)) (0.2.3)
Collecting pyarrow==24.0.0 (from -r requirements.txt (line 111))
  Using cached pyarrow-24.0.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting pycparser==3.0 (from -r requirements.txt (line 112))
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pydeck==0.9.2 (from -r requirements.txt (line 113))
  Using cached pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pygments==2.20.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 114)) (2.20.0)
Collecting pyparsing==3.3.2 (from -r requirements.txt (line 115))
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil==2.9.0.post0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 116)) (2.9.0.post0)
Collecting python-json-logger==4.1.0 (from -r requirements.txt (line 117))
  Using cached python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting python-multipart==0.0.29 (from -r requirements.txt (line 118))
  Using cached python_multipart-0.0.29-py3-none-any.whl.metadata (2.1 kB)
Collecting PyYAML==6.0.3 (from -r requirements.txt (line 119))
  Using cached pyyaml-6.0.3-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: pyzmq==27.1.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 120)) (27.1.0)
Collecting referencing==0.37.0 (from -r requirements.txt (line 121))
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting regex==2026.5.9 (from -r requirements.txt (line 122))
  Using cached regex-2026.5.9-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting requests==2.34.2 (from -r requirements.txt (line 123))
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting rfc3339-validator==0.1.4 (from -r requirements.txt (line 124))
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator==0.1.1 (from -r requirements.txt (line 125))
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting rfc3987-syntax==1.1.0 (from -r requirements.txt (line 126))
  Using cached rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting rich==15.0.0 (from -r requirements.txt (line 127))
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting rpds-py==2026.5.1 (from -r requirements.txt (line 128))
  Using cached rpds_py-2026.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting safetensors==0.7.0 (from -r requirements.txt (line 129))
  Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting scikit-learn==1.8.0 (from -r requirements.txt (line 130))
  Using cached scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting scipy==1.17.1 (from -r requirements.txt (line 131))
  Using cached scipy-1.17.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting Send2Trash==2.1.0 (from -r requirements.txt (line 132))
  Using cached send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting sentence-transformers==5.5.1 (from -r requirements.txt (line 133))
  Using cached sentence_transformers-5.5.1-py3-none-any.whl.metadata (18 kB)
Collecting setuptools==81.0.0 (from -r requirements.txt (line 134))
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting shellingham==1.5.4 (from -r requirements.txt (line 135))
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: six==1.17.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 136)) (1.17.0)
Collecting smmap==5.0.3 (from -r requirements.txt (line 137))

# 🤖 Train Multi-Horizon Model

We will train a multi-output regression model to predict stock close prices for multiple horizons (1, 3, 5, and 10 days ahead). The model will be trained fusioning both technical indicators from the price data and sentiment features extracted from the news articles. We will evaluate the model's performance using appropriate regression metrics to understand its predictive capabilities and limitations.

In [2]:
from src.data_loading import align_news_to_price
from src.data_insights import load_data
from src.feature_engineering import prepare_features, get_llm_embeddings, scale_features
from src.model import train_model, save_model
import pandas as pd
import joblib
from sklearn.metrics import mean_absolute_error, r2_score

2026-05-30 23:28:09.223 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:09.745 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
/workspaces/news-sentiment-analysis-for-stock-price-prediction/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-05-30 23:28:25.659 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:25.661 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:25.662 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:25.663 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:25.665 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

## Prepare data

In [3]:
price_df, news_df = load_data()

df_aligned = align_news_to_price(price_df, news_df)

df_with_emb = get_llm_embeddings(df_aligned)

# Prepare features
df_ready, numeric_cols = prepare_features(df_with_emb)

joblib.dump((df_ready, numeric_cols), 'models/prepared_data.pkl')

# Split train/test
split_date = pd.to_datetime('2024-01-01')
train_df = df_ready[df_ready['date'] < split_date]
test_df = df_ready[df_ready['date'] >= split_date]

target_horizons = [1, 3, 5, 10]
y_train = train_df[[f'target_return_{h}d' for h in target_horizons]].values
y_test = test_df[[f'target_return_{h}d' for h in target_horizons]].values

2026-05-30 23:28:31.509 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:31.510 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-30 23:28:31.640 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:31.738 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-30 23:28:34.018 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:28:34.046 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:02<00:00, 43.65it/s]

Generating embeddings for 1428 unique news texts...

2026-05-30 23:30:51.586 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:30:51.620 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-30 23:30:51.621 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:30:51.698 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

## Scale Features

In [4]:
# Scale features
X_train_scaled, X_test_scaled, scaler = scale_features(
    train_df, test_df, numeric_cols
)

# Save scaler
joblib.dump(scaler, 'models/scaler.pkl')

2026-05-30 23:31:01.490 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-05-30 23:31:01.543 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

['models/scaler.pkl']

## Training

In [5]:
model = train_model(X_train_scaled, y_train)
save_model(model, 'models/regression_model.pkl')

Training on 161 samples with 403 features
Model saved to models/regression_model.pkl

## Evaluate

In [6]:
# Evaluate
y_pred_train = model.predict(X_train_scaled)
y_pred = model.predict(X_test_scaled)

## Results

In [7]:
results_df_train_set = pd.DataFrame({
    'Horizon (days)': target_horizons,
    'MAE': [mean_absolute_error(y_train[:, i], y_pred_train[:, i])
            for i in range(len(target_horizons))],
    'R2': [r2_score(y_train[:, i], y_pred_train[:, i])
           for i in range(len(target_horizons))]
})

results_df_train_set

   Horizon (days)       MAE        R2
0               1  0.000357  0.998878
1               3  0.000321  0.999681
2               5  0.000358  0.999726
3              10  0.000362  0.999852

In [8]:
results_df_test_set = pd.DataFrame({
    'Horizon (days)': target_horizons,
    'MAE': [mean_absolute_error(y_test[:, i], y_pred[:, i])
            for i in range(len(target_horizons))],
    'R2': [r2_score(y_test[:, i], y_pred[:, i])
           for i in range(len(target_horizons))]
})

results_df_test_set

   Horizon (days)       MAE        R2
0               1  0.016922 -0.047428
1               3  0.029893 -0.072421
2               5  0.039573 -0.077896
3              10  0.057335 -0.050335

In [9]:
feature_importance = model.estimators_[0].feature_importances_
top_features = sorted(zip(numeric_cols, feature_importance), 
                      key=lambda x: x[1], reverse=True)[:10]

top_df = pd.DataFrame(top_features, columns=['Feature', 'Importance']).set_index('Feature')

top_df

              Importance
Feature
news_emb_239    0.031457
news_emb_229    0.016730
news_emb_316    0.015864
news_emb_307    0.014664
news_emb_376    0.012764
news_emb_363    0.012577
news_emb_169    0.011891
news_emb_369    0.011702
news_emb_121    0.010276
news_emb_336    0.010269